db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/gym_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3&autoReconnect=true
db.user=24qz3ET7xziMm6s.root
db.password=frX7xZsMC56koOFh
